# Generated by Django 5.1.6 on 2025-02-27 15:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("request_ddi", "0002_survey_date"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Publisher",
            new_name="Distributor",
        ),
        migrations.RenameField(
            model_name="serie",
            old_name="publisher",
            new_name="distributor",
        ),
    ]
