# Generated by Django 5.1.6 on 2025-03-06 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("request_ddi", "0005_remove_collection_abstract_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="language",
            field=models.CharField(default="", max_length=255),
        ),
    ]
