# Generated by Django 5.1.6 on 2025-03-10 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("request_ddi", "0006_survey_language"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="collection",
            name="serie",
        ),
        migrations.RemoveField(
            model_name="survey",
            name="serie",
        ),
        migrations.AddField(
            model_name="collection",
            name="abstract",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="collection",
            name="distributor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="request_ddi.distributor",
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="collections_photos/"),
        ),
        migrations.CreateModel(
            name="Subcollection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField()),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="subcollections_photos/"),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="request_ddi.collection",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="survey",
            name="subcollection",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="request_ddi.subcollection",
            ),
        ),
        migrations.DeleteModel(
            name="Serie",
        ),
    ]
