# Generated by Django 5.2 on 2025-04-25 06:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("request_ddi", "0010_bindingsurveyrepresentedvariable_is_indexed"),
    ]

    operations = [
        migrations.AddField(
            model_name="conceptualvariable",
            name="is_unique",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="representedvariable",
            name="is_unique",
            field=models.BooleanField(default=False),
        ),
    ]
