# Generated by Django 5.2.1 on 2025-05-21 09:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("request_ddi", "0011_conceptualvariable_is_unique_and_more"),
    ]

    # IMPORTANT to add app name as prefix to constraint names to namespace them.
    # If not, if and when we change app name in the future, we can errors migrating DB
    # saying relation already exists
    operations = [
        migrations.AddConstraint(
            model_name="bindingsurveyrepresentedvariable",
            constraint=models.UniqueConstraint(
                fields=("survey", "variable_name"),
                name="request_ddi_unique_variable_name_per_survey",
            ),
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                fields=("code", "category_label"), name="request_ddi_unique_code_category_link"
            ),
        ),
    ]
