# Generated by Django 5.2.8 on 2025-11-13 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "request_ddi",
            "0012_bindingsurveyrepresentedvariable_unique_variable_name_per_survey_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="BindingVariableCategoryStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("stat", models.IntegerField(default=0)),
                (
                    "binding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="request_ddi.bindingsurveyrepresentedvariable",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="request_ddi.category"
                    ),
                ),
            ],
            options={
                "unique_together": {("binding", "category")},
            },
        ),
    ]
