# Generated by Django 6.0.3 on 2026-03-17 15:01

from django.conf import settings
from django.contrib.postgres.operations import CreateCollation
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request_ddi', '0015_category_missing'),
    ]

    # The idea of collation is to use case and accent insensitive comparisons when
    # doing queries. Here we use und language which stands for undefined that takes
    # care of most accents in European languages.
    #
    # Ref:
    # https://oneuptime.com/blog/post/2026-01-25-postgresql-accent-insensitive-collation/view
    # https://adamj.eu/tech/2023/02/23/migrate-django-postgresql-ci-fields-case-insensitive-collation/
    # https://peter.eisentraut.org/blog/2023/05/16/overview-of-icu-collation-settings
    operations = [
        CreateCollation(
            settings.DB_COLLATION,
            provider="icu",
            locale="und-u-ks-level1",
            deterministic=False,
        ),
    ]
