# Generated by Django 6.0.3 on 2026-03-17 15:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_ddi', '0016_case_accent_insensitive_collation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_label',
            field=models.TextField(db_collation=settings.DB_COLLATION, null=True),
        ),
        migrations.AlterField(
            model_name='representedvariable',
            name='internal_label',
            field=models.CharField(db_collation=settings.DB_COLLATION, max_length=510, null=True),
        ),
        migrations.AlterField(
            model_name='representedvariable',
            name='question_text',
            field=models.TextField(db_collation=settings.DB_COLLATION, null=True),
        ),
    ]
