# Generated by Django 6.0.7 on 2026-07-29 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_ddi', '0017_alter_category_category_label_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='author',
            field=models.TextField(blank=True, null=True),
        ),
    ]
