# Generated by Django 6.1 on 2026-09-02 13:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("request_ddi", "0019_update_collation_ignore_punctuation"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadedDDICFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("doi", models.CharField(max_length=255, unique=True)),
                ("original_filename", models.CharField(max_length=255)),
                ("xml_content", models.TextField()),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
