# Generated by Django 5.1.1 on 2024-09-05 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('code', 'code'), ('text', 'text'), ('numerical', 'numerical'), ('date', 'date')], max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('category_label', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_ref', models.CharField(max_length=255)),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ConceptualVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_label', models.TextField()),
                ('concepts', models.ManyToManyField(related_name='conceptual_variables', to='app.concept')),
            ],
        ),
        migrations.CreateModel(
            name='RepresentedVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('question', 'question'), ('var_internal', 'variable interne'), ('var_recalc', 'variable calcule')], max_length=255)),
                ('question_text', models.TextField(null=True)),
                ('internal_label', models.CharField(max_length=255, null=True)),
                ('categories', models.ManyToManyField(related_name='variables', to='app.category')),
                ('conceptual_var', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.conceptualvariable')),
            ],
        ),
        migrations.CreateModel(
            name='BindingSurveyRepresentedVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField()),
                ('variable_name', models.TextField(unique=True)),
                ('universe', models.TextField()),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.representedvariable')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.survey')),
            ],
        ),
        migrations.CreateModel(
            name='BindingConcept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_bindings', to='app.concept')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_bindings', to='app.concept')),
            ],
            options={
                'unique_together': {('parent', 'child')},
            },
        ),
    ]
