# Generated by Django 5.1.1 on 2024-09-06 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bindingsurveyrepresentedvariable',
            name='variable_name',
            field=models.TextField(),
        ),
    ]
