# Generated by Django 5.1.1 on 2024-09-25 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_bindingsurveyrepresentedvariable_variable_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='type',
        ),
        migrations.AddField(
            model_name='representedvariable',
            name='type_categories',
            field=models.CharField(choices=[('code', 'code'), ('text', 'text'), ('numerical', 'numerical'), ('date', 'date')], default='text', max_length=255),
        ),
    ]
