# Generated by Django 5.1.3 on 2024-11-21 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_category_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='representedvariable',
            name='type_categories',
            field=models.CharField(choices=[('code', 'code'), ('text', 'text'), ('numerical', 'numerical'), ('date', 'date')], max_length=255),
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('abstract', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='series_photos/')),
                ('publisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.publisher')),
            ],
        ),
        migrations.AddField(
            model_name='survey',
            name='serie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.serie'),
        ),
    ]
