# Generated by Django 5.1.1 on 2024-09-25 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_category_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='representedvariable',
            name='type_categories',
            field=models.CharField(choices=[('code', 'code'), ('text', 'text'), ('numerical', 'numerical'), ('date', 'date')], max_length=255),
        ),
    ]
