# Generated by Django 5.1.1 on 2024-10-02 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_serie'),
    ]

    operations = [
        migrations.AddField(
            model_name='bindingsurveyrepresentedvariable',
            name='serie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.serie'),
        ),
    ]
