# Generated by Django 5.1.2 on 2024-10-21 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_bindingsurveyrepresentedvariable_serie'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='serie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.serie'),
        ),
    ]
