# Generated by Django 5.1.2 on 2024-10-22 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_survey_serie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='serie',
        ),
    ]
