# Generated by Django 5.1.7 on 2025-03-18 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_date_survey_date_last_version_survey_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='external_ref',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
