# Generated by Django 5.1.2 on 2024-10-23 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_survey_serie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bindingsurveyrepresentedvariable',
            name='serie',
        ),
        migrations.AddField(
            model_name='survey',
            name='serie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.serie'),
        ),
    ]
