# Generated by Django 5.1.2 on 2024-10-29 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_bindingsurveyrepresentedvariable_serie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='series_photos/'),
        ),
    ]
