# Generated by Django 5.1.2 on 2024-10-30 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_serie_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='abstract',
            field=models.TextField(default='ok'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serie',
            name='publisher',
            field=models.CharField(default='ok'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='serie',
            name='name',
            field=models.CharField(),
        ),
    ]
