# Generated by Django 5.1.3 on 2024-11-14 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_convert_publisher_text_to_object'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serie',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.publisher'),
        ),
    ]
