# Generated by Django 5.2.8 on 2025-11-26 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0013_bindingvariablecategorystat"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="collection",
            name="photo",
        ),
        migrations.RemoveField(
            model_name="subcollection",
            name="photo",
        ),
    ]
