# Generated by Django 5.2.9 on 2025-12-03 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0014_remove_collection_photo_remove_subcollection_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="missing",
            field=models.BooleanField(default=False),
        ),
    ]
